# Generated by Django 5.2.17 on 2026-09-16 15:05

import bills.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_token', models.CharField(default=bills.models.generate_token, max_length=64, unique=True)),
                ('share_token', models.CharField(default=bills.models.generate_token, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('status', models.CharField(choices=[('extracting', 'Extracting'), ('review', 'Review'), ('open', 'Open'), ('locked', 'Locked')], default='extracting', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, upload_to='receipts/')),
                ('printed_total_minor', models.IntegerField(default=0)),
                ('extraction_attempts', models.PositiveSmallIntegerField(default=0)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discount', 'Discount'), ('service_charge', 'Service Charge'), ('tax', 'Tax'), ('rounding', 'Rounding'), ('adjustment', 'Adjustment'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('amount_minor', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='bills.bill')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amount_minor', models.PositiveIntegerField()),
                ('item_discount_minor', models.PositiveIntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bills.bill')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('bill', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bills.bill')),
            ],
            options={
                'unique_together': {('bill', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='bills.bill')),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='bills.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='bills.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ItemClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='bills.lineitem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='bills.participant')),
            ],
            options={
                'unique_together': {('line_item', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.bill')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.participant')),
            ],
            options={
                'unique_together': {('bill', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='SplitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_minor', models.JSONField()),
                ('charges_minor', models.JSONField()),
                ('owed_minor', models.IntegerField()),
                ('paid_minor', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bills.bill')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='bills.participant')),
            ],
            options={
                'unique_together': {('bill', 'participant')},
            },
        ),
    ]
