# Generated by Django 5.2.17 on 2026-09-16 15:22

import bills.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='receipt_image',
            field=models.ImageField(blank=True, upload_to=bills.storage.receipt_upload_path),
        ),
    ]
